class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #ADDED THIS LINE.
  #ADDED THIS LINE AS FEATURE1.
  #ADDED THIS LINE AS FEATURE1 2ND TIME.
  #ADDED THIS LINE AS FEATURE1 3RD TIME.
  #ADDED THIS LINE AS FEATURE1 4TH TIME.
  #ADDED THIS LINE AS FEATURE1 5TH TIME.
  #ADDED THIS LINE AS FEATURE1 6TH TIME.
  #ADDED THIS LINE FROM MASTER 2.
  #ADDED THIS LINE FROM FEATURE 2.
     #ANOTHER LINE FROM FEATURE 2.
  #ADDED THIS LINE FROM FEATURE 2, FOR 2ND COMMIT.
end
